### ISSUE TITLE
[Suggestion] Add an "operation" for attribute benefits (1.20.1)

### ISSUE THREAD

**Issue by LynxGrimbane** [CreativeMD/Spice-of-Life-Onion#26]
It would be great to be able to increase certain attributes by a percentage amount as opposed to a flat amount, as it's easier to balance around in certain situations (e.g. 1 point of "spell power" from iron's spells doubles spell damage, 1 point of attack_damage increases your power by 1 point).

I can circumvent this by using decimals in certain scenarios, but it would be great to have an option to, for example, increase max health by 10% instead of a flat amount.

**Comment by CreativeMD** [comment]
Added this in the newest version, but unfortunately only for 1.21. I tried to port it back to 1.20.1, but it did not work out because updates from CreativeCore are not present in 1.20. Sorry but I cannot be bothered to spent the extra time to backport the entire config system rework. If you cannot switch from1.20 you will have to live without this feature. Hope you can understand my reasoning a bit. Anyway, thanks for your suggestion!
